import { normalizeLocale } from './track-locales.js';

const TRACK_NOTES = {
  en: {
    'Albert Park': 'A temporary park circuit that starts green and bumpy, then gets faster as rubber goes down. Its quick direction changes reward a sharp front end and a brave turn-in.',
    'Shanghai International Circuit': 'Shanghai opens with a tightening spiral of early corners and then launches into one of the longest straights on the calendar. It feels equal parts geometry lesson and slipstream trap.',
    'Suzuka': 'Suzuka is a classic figure-eight driver’s circuit, full of flowing esses, commitment corners, and zero cheap lap time. If a car feels good here, it usually feels good everywhere.',
    'Bahrain International Circuit': 'Bahrain is a desert night race built on traction, braking, and temperature swings. The downhill Turn 10 and long traction zones make setup mistakes painfully obvious.',
    'Jeddah Corniche Circuit': 'Jeddah is the fastest street track in Formula 1, with huge average speed and very little breathing room. It feels like threading a car through walls at Monza pace.',
    'Miami International Autodrome': 'Miami mixes big-speed stadium spectacle with a fiddly technical middle sector. It is wide enough to race hard, but awkward enough to punish lazy placement.',
    'Imola': 'Imola is narrow, old-school, and unforgiving in the best possible way. The lap flows over kerbs and elevation changes, and a small mistake usually grows teeth quickly.',
    'Circuit de Monaco': 'Monaco is all precision and no spare space. The lap is slow on paper, but mentally it is one of the fastest places to run out of margin.',
    'Circuit de Barcelona-Catalunya': 'Barcelona is a balanced all-rounder with long loaded corners and a bit of everything else. It has spent years being the track teams use to find out whether the car is actually honest.',
    'Circuit Gilles Villeneuve': 'Canada is a stop-start, low-downforce favourite built around hard braking and quick exits. One wall even has a permanent record of champions getting too greedy.',
    'Red Bull Ring': 'The Red Bull Ring is short, punchy, and built around three uphill blasts before a downhill rush through fast corners. It packs a lot of overtaking energy into a very small lap.',
    'Silverstone': 'Silverstone is a high-speed classic where rhythm and aero confidence matter more than comfort. Sequences like Maggotts and Becketts feel closer to flying than steering.',
    'Spa-Francorchamps': 'Spa combines giant straights, fast compressions, and weather that can change by sector. A lap here always feels one step away from becoming a story.',
    'Hungaroring': 'The Hungaroring is a tight rhythm circuit with barely any time to relax. It rewards a tidy chassis and punishes anyone who loses the sequence halfway through.',
    'Zandvoort': 'Zandvoort rolls through the dunes like a coaster, complete with banking and constant elevation change. It is modernised, but still feels wonderfully old-school.',
    'Monza': 'Monza is the Temple of Speed: huge full-throttle sections, giant braking zones, and almost no patience for drag. Every lap is basically a negotiation between courage and brake temperature.',
    'Baku City Circuit': 'Baku swings between one of the longest straights in F1 and a medieval old-town bottleneck. Teams spend the whole weekend choosing which half of the lap they want to suffer less in.',
    'Marina Bay': 'Marina Bay is hot, humid, and physically draining even before the walls enter the conversation. The night backdrop is glamorous, the lap itself is a serious workout.',
    'Circuit of the Americas': 'COTA is a greatest-hits remix with a giant uphill Turn 1 and an esses section inspired by other classics. It feels familiar, but the Texas scale gives everything more swagger.',
    'Autodromo Hermanos Rodriguez': 'Mexico’s high altitude makes the air thin, the braking strange, and the top speeds huge. The lap then dives into a stadium section that feels more like theatre than racetrack.',
    'Interlagos': 'Interlagos is short, anti-clockwise, and always seems to exaggerate the drama. Elevation, camber, and the Senna S give it the feeling of a lap that is always in a hurry.',
    'Las Vegas Strip Circuit': 'Las Vegas is all long straights, late-night chill, and high-speed braking on the Strip itself. It looks like a show circuit and still manages to generate real racing problems.',
    'Lusail International Circuit': 'Lusail is a fast, flowing layout borrowed from the language of bike racing. Medium- and high-speed corners dominate, but the long main straight still leaves room to attack.',
    'Yas Marina Circuit': 'Yas Marina trades old-school chaos for clean, modern precision under the lights. It is defined by traction zones, hard braking points, and a polished twilight backdrop.'
  },
  'zh-Hans': {
    'Albert Park': '阿尔伯特公园是一条临时街区赛道，周末初期通常偏滑又偏颠，随着橡胶铺开才会越来越快。它很吃前轴响应，方向变换要干净利落。',
    'Shanghai International Circuit': '上赛最有辨识度的是越收越紧的前两弯，以及后面那条超长直道。前段考线路，后段考尾速和刹车胆量。',
    'Suzuka': '铃鹿是典型的车手赛道，S 弯、Degner、130R 连在一起，几乎没有“白送”的圈速。车在这里好开，通常说明整台车真的做对了。',
    'Bahrain International Circuit': '巴林是一条很看牵引和重刹车稳定性的沙漠夜赛道。下坡外倾的 T10 尤其挑人，设定不对会立刻暴露。',
    'Jeddah Corniche Circuit': '吉达是 F1 里最快的街道赛之一，平均速度高得离谱，墙也离得很近。它像是在蒙扎的速度里，硬塞进一整圈街道赛弯角。',
    'Miami International Autodrome': '迈阿密把体育场式的大开大合和中段技术区揉在了一起。够宽，能拼；也够别扭，稍微放松就会错节奏。',
    'Imola': '伊莫拉狭窄、老派，而且对失误一点也不宽容。赛道靠路肩、起伏和连贯节奏吃饭，小错很容易滚成大错。',
    'Circuit de Monaco': '摩纳哥几乎没有多余空间，整圈都在考极限贴墙和手上精度。纸面速度不高，但精神压力永远是顶格的。',
    'Circuit de Barcelona-Catalunya': '巴塞罗那是一条非常均衡的综合型赛道，高中低速弯都有，所以长期被拿来当“赛车诚实度检测器”。',
    'Circuit Gilles Villeneuve': '加拿大站是典型的低下压力、重刹、强牵引赛道。它节奏停停走走，但墙会把每次贪心都记得很清楚。',
    'Red Bull Ring': '红牛环赛道圈很短，但能量很密。前半段连续上坡冲刺，后半段则是一串下坡高速弯，超车机会和节奏感都很强。',
    'Silverstone': '银石是高速传统名场面集合地，像 Maggotts-Becketts 这样的连续高速变向非常考验空气动力学信心。开好一圈会有点像低空飞行。',
    'Spa-Francorchamps': '斯帕把超长直道、超高速弯和神出鬼没的天气全塞进了一圈里。你很难在这里跑出一圈完全“平静”的单圈。',
    'Hungaroring': '亨格罗林常被说像卡丁车赛道，直线短、节奏紧，几乎没时间喘口气。这里更奖励底盘平衡和连弯节奏，而不是马力。',
    'Zandvoort': '赞德沃特沿着沙丘起伏前进，带着过山车一样的节奏和大倾角弯。它经过现代化改造，但骨子里还是非常 old-school。',
    'Monza': '蒙扎是“速度圣殿”，长时间全油门和几个大重刹区定义了一整圈。这里比的不是谁会磨时间，而是谁敢把速度一直留到刹车点。',
    'Baku City Circuit': '巴库一圈像两条赛道拼在一起：一边是超长主直道，一边是老城区的狭窄慢弯。调校永远在“要直道还是要弯道”之间拉扯。',
    'Marina Bay': '滨海湾又热又湿，街道赛路面还特别折腾人，体能消耗一直是重点。夜景很华丽，但方向盘背后的工作量一点都不轻松。',
    'Circuit of the Americas': '美洲赛道像一条“经典赛道元素混剪”，有夸张上坡的 T1，也有向银石和铃鹿致敬的连续弯。熟悉，但尺度很德州。',
    'Autodromo Hermanos Rodriguez': '墨西哥站的海拔很高，空气稀薄、尾速很夸张，刹车和下压力感受都会变得很特别。最后钻进体育场那一段，更像演出现场。',
    'Interlagos': '英特拉格斯圈短、逆时针，而且总能把比赛戏剧性放大。高低起伏、外倾路面和 Senna S 让它整圈都像在催你快一点。',
    'Las Vegas Strip Circuit': '拉斯维加斯把巨长直道、夜晚低温和大道重刹车摆在同一张桌子上。看起来像秀场，跑起来却是实打实的竞速难题。',
    'Lusail International Circuit': '卢塞尔本来就带着摩托车赛道的基因，整体快速而流畅，中高速弯很多。主直道又足够长，所以进 T1 依然很有攻击性。',
    'Yas Marina Circuit': '亚斯码头是一条很现代、很干净的黄昏赛道，重点在牵引、重刹和出弯效率。它没有太多野性，但节奏和观感都很精致。'
  },
  'zh-Hant': {
    'Albert Park': '阿爾伯特公園是一條臨時街區賽道，週末初期通常偏滑又偏顛，隨著橡膠鋪開才會越來越快。它很吃前軸響應，方向變換要乾淨利落。',
    'Shanghai International Circuit': '上賽最有辨識度的是越收越緊的前兩彎，以及後面那條超長直道。前段考路線，後段考尾速和煞車膽量。',
    'Suzuka': '鈴鹿是典型的車手賽道，S 彎、Degner、130R 連在一起，幾乎沒有「白送」的圈速。車在這裡好開，通常說明整台車真的做對了。',
    'Bahrain International Circuit': '巴林是一條很看牽引和重煞車穩定性的沙漠夜賽道。下坡外傾的 T10 尤其挑人，設定不對會立刻暴露。',
    'Jeddah Corniche Circuit': '吉達是 F1 裡最快的街道賽之一，平均速度高得離譜，牆也離得很近。它像是在蒙扎的速度裡，硬塞進一整圈街道賽彎角。',
    'Miami International Autodrome': '邁阿密把體育場式的大開大合和中段技術區揉在了一起。夠寬，能拼；也夠彆扭，稍微放鬆就會錯節奏。',
    'Imola': '伊莫拉狹窄、老派，而且對失誤一點也不寬容。賽道靠路肩、起伏和連貫節奏吃飯，小錯很容易滾成大錯。',
    'Circuit de Monaco': '摩納哥幾乎沒有多餘空間，整圈都在考極限貼牆和手上精度。紙面速度不高，但精神壓力永遠是頂格的。',
    'Circuit de Barcelona-Catalunya': '巴塞隆納是一條非常均衡的綜合型賽道，高中低速彎都有，所以長期被拿來當「賽車誠實度檢測器」。',
    'Circuit Gilles Villeneuve': '加拿大站是典型的低下壓力、重煞、強牽引賽道。它節奏停停走走，但牆會把每次貪心都記得很清楚。',
    'Red Bull Ring': '紅牛環賽道圈很短，但能量很密。前半段連續上坡衝刺，後半段則是一串下坡高速彎，超車機會和節奏感都很強。',
    'Silverstone': '銀石是高速傳統名場面集合地，像 Maggotts-Becketts 這樣的連續高速變向非常考驗空力信心。開好一圈會有點像低空飛行。',
    'Spa-Francorchamps': '斯帕把超長直道、超高速彎和神出鬼沒的天氣全塞進了一圈裡。你很難在這裡跑出一圈完全「平靜」的單圈。',
    'Hungaroring': '亨格羅林常被說像卡丁車賽道，直線短、節奏緊，幾乎沒時間喘口氣。這裡更獎勵底盤平衡和連彎節奏，而不是馬力。',
    'Zandvoort': '贊德沃特沿著沙丘起伏前進，帶著雲霄飛車一樣的節奏和大傾角彎。它經過現代化改造，但骨子裡還是非常 old-school。',
    'Monza': '蒙扎是「速度聖殿」，長時間全油門和幾個大重煞區定義了一整圈。這裡比的不是誰會磨時間，而是誰敢把速度一直留到煞車點。',
    'Baku City Circuit': '巴庫一圈像兩條賽道拼在一起：一邊是超長主直道，一邊是老城區的狹窄慢彎。調校永遠在「要直道還是要彎道」之間拉扯。',
    'Marina Bay': '濱海灣又熱又濕，街道賽路面還特別折騰人，體能消耗一直是重點。夜景很華麗，但方向盤背後的工作量一點都不輕鬆。',
    'Circuit of the Americas': '美洲賽道像一條「經典賽道元素混剪」，有誇張上坡的 T1，也有向銀石和鈴鹿致敬的連續彎。熟悉，但尺度很德州。',
    'Autodromo Hermanos Rodriguez': '墨西哥站的海拔很高，空氣稀薄、尾速很誇張，煞車和下壓力感受都會變得很特別。最後鑽進體育場那一段，更像演出現場。',
    'Interlagos': '英特拉格斯圈短、逆時針，而且總能把比賽戲劇性放大。高低起伏、外傾路面和 Senna S 讓它整圈都像在催你快一點。',
    'Las Vegas Strip Circuit': '拉斯維加斯把巨長直道、夜晚低溫和大道重煞車擺在同一張桌子上。看起來像秀場，跑起來卻是實打實的競速難題。',
    'Lusail International Circuit': '盧塞爾本來就帶著摩托車賽道的基因，整體快速而流暢，中高速彎很多。主直道又足夠長，所以進 T1 依然很有攻擊性。',
    'Yas Marina Circuit': '亞斯碼頭是一條很現代、很乾淨的黃昏賽道，重點在牽引、重煞和出彎效率。它沒有太多野性，但節奏和觀感都很精緻。'
  },
  ja: {
    'Albert Park': 'アルバート・パークは仮設らしく週末序盤は滑りやすくバンピーで、ラバーが乗るほど速くなる。切り返しでは鋭いフロントの反応がものを言う。',
    'Shanghai International Circuit': '上海は締まり続ける序盤のコーナーと、その後に続く超ロングストレートが最大の特徴。前半はライン取り、後半は最高速とブレーキング勝負になる。',
    'Suzuka': '鈴鹿はS字、デグナー、130Rが連なる典型的なドライバーズサーキット。ここで乗りやすいマシンは、だいたいどこでも速い。',
    'Bahrain International Circuit': 'バーレーンはトラクションと重いブレーキング安定性が問われる砂漠のナイトレース。下りながら外傾するターン10が特にセットアップの粗を暴く。',
    'Jeddah Corniche Circuit': 'ジェッダはF1屈指の超高速ストリートで、平均速度は異様に高く壁も近い。モンツァ級の速さで市街地のコーナーを縫っていく感覚だ。',
    'Miami International Autodrome': 'マイアミはスタジアム的な派手さと中盤のテクニカル区間が同居する。幅はあるので仕掛けられるが、少し気を抜くとすぐリズムを外す。',
    'Imola': 'イモラは狭くて古典的、それでいてミスにまったく寛容ではない。縁石と起伏、連続するリズムをきれいにつなげないと、小さな乱れがすぐ大きくなる。',
    'Circuit de Monaco': 'モナコは余白ゼロの精密作業サーキット。紙の上では低速でも、精神的には最速級に余裕がなくなる場所だ。',
    'Circuit de Barcelona-Catalunya': 'バルセロナは高速・中速・低速が揃った総合テストサーキット。マシンが本当に素直かどうかを長年見抜いてきた。',
    'Circuit Gilles Villeneuve': 'カナダは低ダウンフォースで、強いブレーキングと立ち上がりの鋭さが求められるストップ＆ゴー型。壁は欲張りをしっかり記録してくれる。',
    'Red Bull Ring': 'レッドブル・リンクは短いのに密度が高い。前半は登りの全開区間、後半は下りの高速コーナー群で、短いラップにオーバーテイク要素が詰まっている。',
    'Silverstone': 'シルバーストンはリズムと空力への信頼が問われる高速クラシック。マゴッツ-ベケッツのような連続区間は、操縦というより低空飛行に近い。',
    'Spa-Francorchamps': 'スパは長いストレート、高速コーナー、そして読みにくい天候を一周に詰め込んだ場所。ここで静かなラップを走るのはほぼ不可能だ。',
    'Hungaroring': 'ハンガロリンクは直線が短く、休む暇のないリズム重視のサーキット。馬力よりもシャシーのまとまりと連続コーナーの精度がものを言う。',
    'Zandvoort': 'ザントフォールトは砂丘の起伏に沿ってうねる、ジェットコースターのようなレイアウト。近代化されても芯はしっかりオールドスクールのままだ。',
    'Monza': 'モンツァは“スピードの殿堂”。長い全開区間と大きなブレーキングで一周が定義され、どこまで速度を持ち込めるかの勇気が問われる。',
    'Baku City Circuit': 'バクーは超ロングストレートと旧市街の超低速区間が同居する二面性のサーキット。セットアップは結局、どちらを少し我慢するかの選択になる。',
    'Marina Bay': 'マリーナベイは蒸し暑く、路面も荒れ気味で、壁抜きでも体力勝負になるナイトレース。見た目は華やかでも、ドライバーの仕事量はかなり重い。',
    'Circuit of the Americas': 'COTAは名サーキット要素のリミックス版のような一周で、大きな上りのターン1と連続エッセが印象的。見覚えはあるのに、スケール感は完全にテキサスだ。',
    'Autodromo Hermanos Rodriguez': 'メキシコは高地ゆえ空気が薄く、最高速もブレーキング感覚も独特になる。最後のスタジアム区間はレースというよりショーの舞台に近い。',
    'Interlagos': 'インテルラゴスは短い反時計回りの一周に、起伏とドラマをぎゅっと詰め込んだサーキット。セナSを抜ける頃には、常に急かされているような気分になる。',
    'Las Vegas Strip Circuit': 'ラスベガスは長いストレート、夜の低温、そしてストリップ上の重いブレーキングが同居する。見た目はショーでも、中身はしっかりレースの難題だ。',
    'Lusail International Circuit': 'ルサイルはもともと二輪向けらしい高速で流れるようなレイアウト。中高速コーナーが多い一方で、メインストレートはターン1への攻めどころを残している。',
    'Yas Marina Circuit': 'ヤス・マリーナは近代的で整った黄昏のサーキットで、トラクションと重いブレーキングが肝になる。荒々しさは少ないが、リズムと見栄えは非常に洗練されている。'
  },
  ko: {
    'Albert Park': '앨버트 파크는 임시 서킷답게 주말 초반에는 미끄럽고 노면이 거칠지만, 고무가 깔릴수록 점점 빨라진다. 빠른 방향 전환에서는 날카로운 프런트 반응이 중요하다.',
    'Shanghai International Circuit': '상하이는 조여 들어가는 초반 코너와 그 뒤를 잇는 초장거리 직선이 가장 큰 특징이다. 전반부는 라인 싸움, 후반부는 최고속과 브레이킹 승부가 된다.',
    'Suzuka': '스즈카는 S코너, 데그너, 130R이 이어지는 전형적인 드라이버 서킷이다. 여기서 타기 좋은 차는 대체로 어디서든 잘 달린다.',
    'Bahrain International Circuit': '바레인은 트랙션과 강한 제동 안정성이 중요한 사막의 나이트 레이스다. 내리막 외캠버인 10번 코너가 특히 세팅의 허점을 잘 드러낸다.',
    'Jeddah Corniche Circuit': '제다는 F1에서 손꼽히는 초고속 스트리트 서킷으로 평균 속도는 매우 높고 벽은 가깝다. 몬차급 속도로 시가지 코너를 꿰매는 느낌에 가깝다.',
    'Miami International Autodrome': '마이애미는 스타디움형 스펙터클과 중반 테크니컬 구간이 함께 있는 서킷이다. 폭은 넓어 과감히 싸울 수 있지만, 조금만 흐트러져도 바로 리듬이 깨진다.',
    'Imola': '이몰라는 좁고 올드스쿨하며 실수에 전혀 관대하지 않다. 연석과 고저차, 이어지는 리듬을 깔끔하게 묶지 못하면 작은 실수가 곧바로 커진다.',
    'Circuit de Monaco': '모나코는 여유 공간이 전혀 없는 정밀 작업형 서킷이다. 속도표만 보면 느려 보여도, 정신적인 압박은 가장 빠른 곳 중 하나다.',
    'Circuit de Barcelona-Catalunya': '바르셀로나는 고속·중속·저속이 다 들어 있는 균형형 서킷이다. 차가 정말 정직한지 오랫동안 판별해 온 기준점 같은 곳이다.',
    'Circuit Gilles Villeneuve': '캐나다는 저다운포스 성향의 스톱앤고 서킷으로, 강한 제동과 날카로운 탈출 가속이 중요하다. 벽은 욕심낸 순간을 아주 잘 기억한다.',
    'Red Bull Ring': '레드불 링은 짧지만 밀도가 높다. 전반부는 오르막 풀스로틀 구간, 후반부는 내리막 고속 코너로 이어져 짧은 랩 안에 추월 포인트가 가득하다.',
    'Silverstone': '실버스톤은 리듬과 공력 신뢰가 중요한 고속 클래식이다. 매고츠-베케츠 같은 구간은 조향이라기보다 저공비행에 가깝게 느껴진다.',
    'Spa-Francorchamps': '스파는 긴 직선과 초고속 코너, 그리고 예측하기 어려운 날씨를 한 바퀴에 모두 담고 있다. 여기서 조용한 랩을 만들기란 거의 불가능하다.',
    'Hungaroring': '헝가로링은 직선이 짧고 쉬는 구간이 거의 없는 리듬 서킷이다. 마력보다 차체 균형과 연속 코너에서의 정확성이 더 중요하다.',
    'Zandvoort': '잔드보르트는 모래언덕을 따라 롤러코스터처럼 요동치는 레이아웃에 뱅킹과 고저차까지 더해진다. 현대화됐어도 본질은 여전히 강한 올드스쿨이다.',
    'Monza': '몬차는 “스피드의 성전”이다. 긴 풀스로틀 구간과 큰 제동 존이 한 바퀴를 정의하며, 얼마나 오래 속도를 들고 갈 수 있는지가 승부를 가른다.',
    'Baku City Circuit': '바쿠는 초장거리 직선과 구시가지의 초저속 구간이 공존하는 양면적인 서킷이다. 세팅은 결국 어느 쪽을 조금 더 참을지 선택하는 문제다.',
    'Marina Bay': '마리나 베이는 덥고 습하며 노면도 거칠어, 벽을 빼더라도 체력전이 되는 야간 스트리트 레이스다. 화려해 보여도 드라이버의 작업량은 상당히 크다.',
    'Circuit of the Americas': 'COTA는 명서킷 요소를 섞어 놓은 듯한 한 바퀴로, 큰 오르막의 1코너와 연속 에스가 특히 인상적이다. 익숙하면서도 스케일은 완전히 텍사스답다.',
    'Autodromo Hermanos Rodriguez': '멕시코는 고지대라 공기가 얇고 최고속과 제동 감각이 모두 독특하다. 마지막 스타디움 구간은 레이스라기보다 하나의 공연장에 가깝다.',
    'Interlagos': '인터라고스는 짧은 반시계 랩 안에 고저차와 드라마를 진하게 압축한 서킷이다. 세나 S를 지나갈 즈음이면 늘 무언가가 서두르게 만든다.',
    'Las Vegas Strip Circuit': '라스베이거스는 긴 직선, 밤의 낮은 노면 온도, 그리고 스트립 위의 큰 제동이 한데 모인다. 겉보기엔 쇼 같아도, 실제로는 꽤 까다로운 레이스 문제를 던진다.',
    'Lusail International Circuit': '루사일은 원래 이륜 레이스용답게 빠르고 흐르는 레이아웃이 특징이다. 중고속 코너가 많지만 메인 스트레이트는 1코너 공략 여지를 충분히 남긴다.',
    'Yas Marina Circuit': '야스 마리나는 현대적이고 정돈된 황혼 서킷으로, 트랙션과 강한 제동이 핵심이다. 거칠진 않지만 리듬과 완성도는 매우 세련되어 있다.'
  }
};

export function getTrackNote(trackName, locale = 'en') {
  const normalizedLocale = normalizeLocale(locale);
  return TRACK_NOTES[normalizedLocale]?.[trackName]
    ?? TRACK_NOTES.en[trackName]
    ?? '';
}
